# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#

default: &default
  adapter: postgresql
  encoding: unicode
  database: myapp_dev
  pool: 5
  username: sampleuser
  password: md57c29ff67c2c792ffd18918ca5ea66071

development:
  adapter: postgresql
  encoding: unicode
  database: myapp_dev
  pool: 5
  username: sampleuser
  password: md57c29ff67c2c792ffd18918ca5ea66071

test:
  adapter: postgresql
  encoding: unicode
  database: myapp_test
  pool: 5
  username: sampleuser
  password: md57c29ff67c2c792ffd18918ca5ea66071

production:
  adapter: postgresql
  encoding: unicode
  database: myapp_dev
  pool: 5
  username: sampleuser
  password: md57c29ff67c2c792ffd18918ca5ea66071
