# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 255b616c9d3cbc7a4668797d28929ab39f3ef122482198db0f59aeb6223cb9a6f6fb5af613982a3454cc820486b604445f2464b3c6bb6df62c945c595691780b

test:
  secret_key_base: 28237846337a94133a4aa131e899427a25c5109d39a0d37e1fd496a9efd37c34658a278ad4fc726ec563c69cc7fc70dd000b6784f2277c84ca0a982d22af67b4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
